version: "3"

services:

    express:
        build: ./express-generator
        environment:
            - PORT=5000
        ports:
            - 5000:5000
        volumes:
            - ./express-generator:/app
            - ./express-generator/node_modules:/app/node_modules

    frontend:
        build: ./frontend
        environment:
            - PORT=3000
        ports: 
            - 3000:3000
        volumes:
            - ./frontend:/src:/app/src
            - /app/node_modules

    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend
